// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineWalmart.DAL;

#nullable disable

namespace OnlineWalmart.Migrations
{
    [DbContext(typeof(ProductContext))]
    partial class ProductContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("OnlineWalmart.DAL.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("DeliveryInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Discount")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("569a37e6-4bef-4619-bafc-48533e9c86a5"),
                            DeliveryInfo = "Delivery with Instabox within 0-2 working days",
                            Description = "Cedar wood",
                            Discount = 0.0,
                            Name = "Wooden Spatula",
                            Price = 14.35
                        },
                        new
                        {
                            Id = new Guid("3de11058-7854-4473-9404-17bfeb480af5"),
                            DeliveryInfo = "Come and pick up in our store within 14 days.",
                            Description = "Very ecological and efficient",
                            Discount = 0.0,
                            Name = "Jumprope",
                            Price = 12.15
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
