// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineWalmart.Users.Context;

#nullable disable

namespace OnlineWalmart.Users.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20220421115014_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("OnlineWalmart.Users.DAL.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTimeOffset>("DateOfBirth")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a93b839a-14dc-4d36-8b1e-6119fafe9d5a"),
                            DateOfBirth = new DateTimeOffset(new DateTime(1985, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "billy@nomail.com",
                            FirstName = "Billy",
                            LastName = "Bob",
                            Phone = "0763648234"
                        },
                        new
                        {
                            Id = new Guid("2c53aafa-e8e2-4496-89b4-6b9a4d301c03"),
                            DateOfBirth = new DateTimeOffset(new DateTime(1982, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "john@nomail.com",
                            FirstName = "John",
                            LastName = "Doe",
                            Phone = "0765628331"
                        },
                        new
                        {
                            Id = new Guid("361efbef-13bd-44fe-929d-917e71d0e5e7"),
                            DateOfBirth = new DateTimeOffset(new DateTime(1995, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "jane@nomail.com",
                            FirstName = "Jane",
                            LastName = "Doe",
                            Phone = "0765628331"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
